GET http://localhost:3000/players/

##33
GET http://localhost:3000/players/12/ 

####
PUT http://localhost:3000/players/12/ 
 
#####
GET http://localhost:3000/matches/3/

###
GET http://localhost:3000/players/5/matches/

#######
GET http://localhost:3000/matches/4/players/

#####
GET http://localhost:3000/players/12/playerScores/

